CREATE TABLE roles (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) UNIQUE NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by VARCHAR(150) NOT NULL,
  branch_id INT NULL
);

CREATE TABLE branches (
  id INT AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(20) UNIQUE NOT NULL,
  name VARCHAR(120) NOT NULL,
  city_municipality VARCHAR(120) NOT NULL,
  contact_email VARCHAR(150) NOT NULL,
  contact_number VARCHAR(50) NOT NULL,
  logo_url VARCHAR(300),
  announcement_theme TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by VARCHAR(150) NOT NULL,
  branch_id INT NULL
);

CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(150) UNIQUE NOT NULL,
  full_name VARCHAR(150) NOT NULL,
  role_id INT NOT NULL,
  role VARCHAR(50) NOT NULL,
  branch_code VARCHAR(20),
  password_hash VARCHAR(255) NOT NULL,
  is_active BOOLEAN DEFAULT TRUE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by VARCHAR(150) NOT NULL,
  branch_id INT NULL,
  FOREIGN KEY (role_id) REFERENCES roles(id)
);

CREATE TABLE services (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(180) NOT NULL,
  slug VARCHAR(180) UNIQUE NOT NULL,
  description TEXT NOT NULL,
  eligibility TEXT NOT NULL,
  processing_days INT DEFAULT 3,
  is_active BOOLEAN DEFAULT TRUE,
  branch_code VARCHAR(20),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by VARCHAR(150) NOT NULL,
  branch_id INT NULL
);

CREATE TABLE citizen_charter (
  id INT AUTO_INCREMENT PRIMARY KEY,
  service_id INT NOT NULL,
  title VARCHAR(180) NOT NULL,
  requirements TEXT NOT NULL,
  steps TEXT NOT NULL,
  standard_processing_hours INT DEFAULT 72,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by VARCHAR(150) NOT NULL,
  branch_id INT NULL,
  FOREIGN KEY (service_id) REFERENCES services(id)
);

CREATE TABLE applications (
  id INT AUTO_INCREMENT PRIMARY KEY,
  reference_no VARCHAR(50) UNIQUE NOT NULL,
  service_id INT NOT NULL,
  applicant_name VARCHAR(180) NOT NULL,
  applicant_email VARCHAR(150) NOT NULL,
  branch_code VARCHAR(20) NOT NULL,
  status VARCHAR(50) DEFAULT 'Submitted',
  payload JSON NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by VARCHAR(150) NOT NULL,
  branch_id INT NULL,
  FOREIGN KEY (service_id) REFERENCES services(id)
);

CREATE TABLE application_status_history (
  id INT AUTO_INCREMENT PRIMARY KEY,
  application_id INT NOT NULL,
  from_status VARCHAR(50) NOT NULL,
  to_status VARCHAR(50) NOT NULL,
  remarks TEXT,
  changed_by VARCHAR(150) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by VARCHAR(150) NOT NULL,
  branch_id INT NULL,
  FOREIGN KEY (application_id) REFERENCES applications(id)
);

CREATE TABLE documents (
  id INT AUTO_INCREMENT PRIMARY KEY,
  application_id INT NOT NULL,
  file_name VARCHAR(255) NOT NULL,
  mime_type VARCHAR(100) NOT NULL,
  file_size_bytes INT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by VARCHAR(150) NOT NULL,
  branch_id INT NULL,
  FOREIGN KEY (application_id) REFERENCES applications(id)
);

CREATE TABLE announcements (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(180) NOT NULL,
  body TEXT NOT NULL,
  target_scope VARCHAR(50) DEFAULT 'province',
  target_branch_code VARCHAR(20),
  audience VARCHAR(30) DEFAULT 'public',
  publish_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  expires_at DATETIME,
  is_active BOOLEAN DEFAULT TRUE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by VARCHAR(150) NOT NULL,
  branch_id INT NULL
);

CREATE TABLE ledgers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  entry_type VARCHAR(50) NOT NULL,
  reference_no VARCHAR(50) NOT NULL,
  branch_code VARCHAR(20) NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  description TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by VARCHAR(150) NOT NULL,
  branch_id INT NULL
);

CREATE TABLE audit_logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  action VARCHAR(100) NOT NULL,
  object_type VARCHAR(80) NOT NULL,
  object_id VARCHAR(80) NOT NULL,
  details TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by VARCHAR(150) NOT NULL,
  branch_id INT NULL
);
